flywayDesktop = { }

[redgateCompare]
filterFile = "filter.rgf"

[environments.development]
user = "clqadmin"
password = "${localSecret.Flyway Desktop 3b688166-3cb6-40c3-8c61-38df4580a526}"

[environments.shadow]
user = "clqadmin"
password = "${localSecret.Flyway Desktop 2752ba5a-49fe-4b7e-aa77-e528aaf604be}"
