SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[ExampleTable]'
GO
CREATE TABLE [dbo].[ExampleTable]
(
[id] [int] NOT NULL IDENTITY(1, 1),
[testcolumn] [varchar] (255) NULL
)
GO

