SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Altering [dbo].[ExampleTable]'
GO
ALTER TABLE [dbo].[ExampleTable] ADD
[anothercolumn] [varchar] (1) NULL
GO

